Update AndroidManifest.xml
```
2026-05-08 09:41:23.248 27002-27002 AndroidRuntime          io.github.goooler.tabby              E  FATAL EXCEPTION: main
Process: io.github.goooler.tabby:background, PID: 27002
java.lang.RuntimeException: Unable to instantiate application com.github.kr328.clash.app.MainApplication package io.github.goooler.tabby
	at android.app.LoadedApk.throwForNewApplicationFailure(LoadedApk.java:1685)
	at android.app.LoadedApk.onNewApplicationFailed(LoadedApk.java:1675)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1640)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1568)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8124)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2716)
	at android.os.Handler.dispatchMessageImpl(Handler.java:142)
	at android.os.Handler.dispatchMessage(Handler.java:125)
	at android.os.Looper.loopOnce(Looper.java:269)
	at android.os.Looper.loop(Looper.java:367)
	at android.app.ActivityThread.main(ActivityThread.java:9333)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:929)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.kr328.clash.app.MainApplication" on path: DexPathList[[zip file "/data/app/~~EWCt1QJ-XjhTKcdkg5v47g==/io.github.goooler.tabby-tqabdFfkznufnRbKWZ6Q2Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~EWCt1QJ-XjhTKcdkg5v47g==/io.github.goooler.tabby-tqabdFfkznufnRbKWZ6Q2Q==/lib/arm64, /data/app/~~EWCt1QJ-XjhTKcdkg5v47g==/io.github.goooler.tabby-tqabdFfkznufnRbKWZ6Q2Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:642)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:578)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:78)
	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:51)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1362)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1636)
	... 12 more
---------------------------- PROCESS ENDED (27002) for package io.github.goooler.tabby ----------------------------
```